# Generated by Django 3.1.6 on 2021-02-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='search_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
