# Generated by Django 3.1.6 on 2021-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210208_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
