# Generated by Django 3.1.6 on 2021-02-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210208_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
