# Generated by Django 3.1.6 on 2021-02-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210210_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='discount',
        ),
    ]
