# Generated by Django 3.1.6 on 2021-02-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderdetail_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
